import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const projectRoot = path.resolve(import.meta.dirname, '..');
const repositoryRoot = path.resolve(projectRoot, '..', '..');
const legacySourceRoot = path.join(repositoryRoot, 'src');
const legacyGameRoot = path.join(legacySourceRoot, 'game');
const publicRoot = path.join(projectRoot, 'public');

const sourceFiles = (await readdir(legacyGameRoot))
  .filter((name) => /^\d{2}-.+\.js$/.test(name))
  .sort((a, b) => a.localeCompare(b, 'en'));

if (sourceFiles.length === 0) {
  throw new Error(`No ordered legacy sources found in ${legacyGameRoot}`);
}

const legacySources = await Promise.all(
  sourceFiles.map((name) => readFile(path.join(legacyGameRoot, name), 'utf8'))
);
const bridge = await readFile(path.join(projectRoot, 'src', 'legacy-bridge.js'), 'utf8');
const styles = await readFile(path.join(legacySourceRoot, 'styles.css'), 'utf8');
const banner = [
  '// Generated by scripts/prepare-legacy.mjs.',
  '// Edit ../../src/game/*.js or src/legacy-bridge.js, then regenerate.',
  ''
].join('\n');

await mkdir(publicRoot, { recursive: true });
await Promise.all([
  writeFile(
    path.join(publicRoot, 'legacy-game.js'),
    `${banner}${legacySources.join('\n\n')}\n\n${bridge}\n`,
    'utf8'
  ),
  writeFile(path.join(publicRoot, 'legacy-styles.css'), styles, 'utf8')
]);

console.log(
  `Prepared ${sourceFiles.length} legacy game modules, bridge, and stylesheet in v2/skyfire-three/public/.`
);
